/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuAbsen;

import static MenuAbsen.AbsenDkv.IdSCDKV;
import static MenuAbsen.AbsenDkv.playSound;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import smartcard1.LoginGuru;
import smartcard1.PilihMapel;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Haydar Dzaky S
 */
public class AbsenArab extends javax.swing.JFrame {

    /**
     * Creates new form AbsenArab
     */
    public static String IdSCArab = null;
    
    public AbsenArab() {
        this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        initComponents();
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        
        this.setSize(xsize, ysize);
    }
    
    private void absen(){
        
        Connection con;
        PreparedStatement ps;
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://103.28.13.26:3306/aris_UbkSantri", "aris_UbkSantri", "MyJava17");
            ps = con.prepareStatement("SELECT * FROM TbStudent WHERE StudentSmartCard = ?");
            ps.setString(1, txtIdSCDkv.getText());
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                new FinalDkv().setVisible(true);  
                this.setVisible(false);
            } else {
                playSound("sound\\\\unauthorized.wav");
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginGuru.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public static void playSound(String filepath){
        
        InputStream music;
        
        try {
            music = new FileInputStream(new File(filepath));
            AudioStream audioS = new AudioStream(music);
            AudioPlayer.player.start(audioS);
            
        } catch (Exception ex) {
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jText3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdSCDkv = new javax.swing.JTextField();
        jText2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/logomss.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 50, 350, 90);

        jText3.setFont(new java.awt.Font("Verdana", 0, 50)); // NOI18N
        jText3.setForeground(new java.awt.Color(255, 255, 255));
        jText3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jText3.setText("Selesai");
        jText3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jText3);
        jText3.setBounds(120, 210, 180, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/button.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 200, 350, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/tap.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 190, 280, 380);

        txtIdSCDkv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdSCDkvKeyPressed(evt);
            }
        });
        getContentPane().add(txtIdSCDkv);
        txtIdSCDkv.setBounds(880, 360, 220, 0);

        jText2.setFont(new java.awt.Font("Verdana", 0, 40)); // NOI18N
        jText2.setForeground(new java.awt.Color(255, 255, 255));
        jText2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jText2.setText("Tap your card to continue");
        jText2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jText2);
        jText2.setBounds(440, 610, 530, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/bgfinl.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, -10, 1380, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        new PilihMapel().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txtIdSCDkvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdSCDkvKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            IdSCArab = txtIdSCDkv.getText();
            absen();

        }
    }//GEN-LAST:event_txtIdSCDkvKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbsenArab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbsenArab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbsenArab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbsenArab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbsenArab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jText2;
    private javax.swing.JLabel jText3;
    private javax.swing.JTextField txtIdSCDkv;
    // End of variables declaration//GEN-END:variables
}
