/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartcard1;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static MenuAbsen.AbsenDkv.playSound;

/**
 *
 * @author Haydar Dzaky S
 */
public class LoginGuru extends javax.swing.JFrame {

    /**
     * Creates new form LoginGuru
     */
    public static String IdSC = null;
    
    public LoginGuru() {
        this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        
        initComponents();
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        
        this.setSize(xsize, ysize);
        
       
    }
    
    public Connection getConnection(){
        
        Connection con = null;
            
        try {
            con = DriverManager.getConnection("jdbc:mysql://103.28.13.26:3306/aris_UbkSantri", "aris_UbkSantri", "MyJava17");
            return con;
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginGuru.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Not Connected");
            return null;
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdSmartCard = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jText2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        txtIdSmartCard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdSmartCardKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdSmartCardKeyReleased(evt);
            }
        });
        getContentPane().add(txtIdSmartCard);
        txtIdSmartCard.setBounds(1050, 400, 150, 0);

        btnExit.setText("EXIT");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(1210, 660, 90, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/logomss.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 350, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/tap.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 190, 280, 380);

        jText2.setFont(new java.awt.Font("Verdana", 0, 40)); // NOI18N
        jText2.setForeground(new java.awt.Color(255, 255, 255));
        jText2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jText2.setText("Tap your card to continue");
        jText2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jText2);
        jText2.setBounds(440, 610, 530, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/bgfinl.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 1380, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void txtIdSmartCardKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdSmartCardKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSmartCardKeyReleased

    private void txtIdSmartCardKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdSmartCardKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            IdSC = txtIdSmartCard.getText();
            login();

        }
    }//GEN-LAST:event_txtIdSmartCardKeyPressed

    
    public void login(){
        
        Connection con;
        PreparedStatement ps;
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://103.28.13.26:3306/aris_UbkSantri", "aris_UbkSantri", "MyJava17");
            ps = con.prepareStatement("SELECT * FROM TbLogin WHERE IdSmartCard = ?");
            ps.setString(1, txtIdSmartCard.getText());
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                new PilihMapel().setVisible(true);  
                this.setVisible(false);
            } else {
                playSound("sound\\\\unauthorized.wav");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginGuru.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGuru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jText2;
    private javax.swing.JTextField txtIdSmartCard;
    // End of variables declaration//GEN-END:variables
}
