/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartcard1;

import AbsenHelper.CekHadirDkv;
import java.awt.Image;
import smartcard1.Menu.MenuDkv;
import java.awt.Toolkit;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static smartcard1.LoginGuru.IdSC;
import smartcard1.Menu.MenuAkhlak;
import smartcard1.Menu.MenuArab;
import smartcard1.Menu.MenuDev;
import smartcard1.Menu.MenuFiqih;
import smartcard1.Menu.MenuInggris;
import smartcard1.Menu.MenuKemandirian;
import smartcard1.Menu.MenuQcb;
import smartcard1.Menu.MenuTajwid;

/**
 *
 * @author Haydar Dzaky S
 */
public class PilihMapel extends javax.swing.JFrame {

    /**
     * Creates new form PilihMapel
     */
    
    public PilihMapel() {
        this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        
        initComponents();
        data();
        availableDkv();
        clock();
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        
        this.setSize(xsize, ysize);
       
    }
    
    String ImgPath = null;

    public Connection getConnection(){
        
        Connection con = null;
            
        try {
            con = DriverManager.getConnection("jdbc:mysql://103.28.13.26:3306/aris_UbkSantri", "aris_UbkSantri", "MyJava17");
            return con;
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginGuru.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Not Connected ");
            return null;
        }
        
    }
    
    public void data(){
        
        try {
            Connection con = getConnection();
            PreparedStatement ps = con.prepareStatement ("SELECT * FROM TbLogin WHERE IdSmartCard = '" +IdSC+ "'");
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                String mUstad = rs.getString("TeacherName");
                mNamaUstad.setText(mUstad);
                
                String mStatus = rs.getString("TeacherStatus");
                txtStatus.setText(mStatus);
                
                byte[] img = rs.getBytes("TeacherPic");
                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImage = im.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImage);
                lblImage.setIcon(newImage);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(PilihMapel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
   
    
    public void availableDkv(){
        
            Calendar c = Calendar.getInstance();    
            int dayOfWeek = c.get(Calendar.DAY_OF_WEEK);
            
            String today = Integer.toString(dayOfWeek);
            
            System.out.println(today);
        
    }
    
    public void clock(){
        
        Thread clock = new Thread(){
            
            public void run(){
                
                try{
                    for(;;){
                    Calendar cal = new GregorianCalendar();
        
                    int hour = cal.get(Calendar.HOUR);
                    int minute = cal.get(Calendar.MINUTE);
                    int second = cal.get(Calendar.SECOND);
        
                    txtClock.setText(""+hour+":"+minute+":"+second+"");
                    
                    sleep(100);
                    }
                } catch(InterruptedException e) {
                    //TODO Auto-generated catch block
                    e.printStackTrace();
                    
                }
                
        }
            
        };
        
        clock.start();
        
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        mNamaUstad = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtClock = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        btnDKV = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jButton4.setText("jButton1");

        jButton8.setText("jButton1");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/buttonlesson.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 100)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Teacher");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 920, 410, 150);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 100)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Logout");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 1220, 360, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/button.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 1200, 690, 86);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 100)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Cek Kehadiran Santri");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1250, 1300, 1080, 110);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/ceksantri.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1110, 1280, 1350, 150);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/dummy.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1134, 904, 1320, 260);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/logomss.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 40, 350, 110);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 45)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Logout");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(140, 610, 150, 70);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/button.png"))); // NOI18N
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(btnLogout);
        btnLogout.setBounds(40, 600, 354, 100);

        txtStatus.setFont(new java.awt.Font("Verdana", 0, 50)); // NOI18N
        txtStatus.setForeground(new java.awt.Color(255, 255, 255));
        txtStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtStatus.setText("Teacher");
        getContentPane().add(txtStatus);
        txtStatus.setBounds(60, 500, 300, 60);

        mNamaUstad.setFont(new java.awt.Font("Verdana", 0, 50)); // NOI18N
        mNamaUstad.setForeground(new java.awt.Color(255, 255, 255));
        mNamaUstad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mNamaUstad.setText("Ustad");
        mNamaUstad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(mNamaUstad);
        mNamaUstad.setBounds(20, 410, 380, 60);

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 45)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 153, 204));
        jLabel27.setText("Cek Kehadiran Santri");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(690, 650, 550, 70);

        txtClock.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        txtClock.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtClock);
        txtClock.setBounds(1100, 30, 240, 40);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/ceksantri.png"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel28);
        jLabel28.setBounds(540, 630, 770, 110);

        jLabel30.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 153, 204));
        jLabel30.setText("DKV");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(620, 220, 90, 50);

        btnDKV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/buttonlesson.png"))); // NOI18N
        btnDKV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDKVMouseClicked(evt);
            }
        });
        getContentPane().add(btnDKV);
        btnDKV.setBounds(530, 190, 260, 110);

        jLabel39.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 153, 204));
        jLabel39.setText("Fiqih");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(620, 360, 90, 50);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/buttonlesson.png"))); // NOI18N
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel40);
        jLabel40.setBounds(530, 330, 260, 110);

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 153, 204));
        jLabel31.setText("B. Arab");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(590, 500, 140, 50);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/buttonlesson.png"))); // NOI18N
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel41);
        jLabel41.setBounds(530, 470, 260, 110);

        jLabel33.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 153, 204));
        jLabel33.setText("B. Inggris");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(840, 500, 180, 50);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/buttonlesson.png"))); // NOI18N
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel43MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel43);
        jLabel43.setBounds(800, 470, 260, 110);

        jLabel35.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 153, 204));
        jLabel35.setText("Akhlak");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(870, 360, 140, 50);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/buttonlesson.png"))); // NOI18N
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel44);
        jLabel44.setBounds(800, 330, 260, 110);

        jLabel45.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 153, 204));
        jLabel45.setText("Programming");
        getContentPane().add(jLabel45);
        jLabel45.setBounds(810, 220, 250, 50);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/buttonlesson.png"))); // NOI18N
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel46);
        jLabel46.setBounds(800, 190, 260, 110);

        jLabel36.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 153, 204));
        jLabel36.setText("Tajwid");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(1140, 360, 120, 50);

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/buttonlesson.png"))); // NOI18N
        jLabel49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel49MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel49);
        jLabel49.setBounds(1070, 330, 260, 110);

        jLabel51.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 153, 204));
        jLabel51.setText("Kemandirian");
        getContentPane().add(jLabel51);
        jLabel51.setBounds(1090, 500, 226, 50);

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/buttonlesson.png"))); // NOI18N
        jLabel52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel52MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel52);
        jLabel52.setBounds(1070, 470, 260, 110);

        jLabel38.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 153, 204));
        jLabel38.setText("QCB");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(1160, 220, 90, 50);

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/buttonlesson.png"))); // NOI18N
        jLabel55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel55MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel55);
        jLabel55.setBounds(1070, 190, 260, 110);

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 50)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Choose Lesson");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(740, 90, 390, 50);
        getContentPane().add(lblImage);
        lblImage.setBounds(110, 190, 200, 210);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/bgfinl.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-10, -10, 1380, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        new LoginGuru().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnDKVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDKVMouseClicked
        // TODO add your handling code here:
        new MenuDkv().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDKVMouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        new MenuCekHadir().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        // TODO add your handling code here:
        new MenuAkhlak().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel44MouseClicked

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
        // TODO add your handling code here:
        new MenuArab().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel41MouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        // TODO add your handling code here:
        new MenuDev().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel46MouseClicked

    private void jLabel55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel55MouseClicked
        // TODO add your handling code here:
        new MenuQcb().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel55MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        // TODO add your handling code here:
        new MenuFiqih().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jLabel49MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel49MouseClicked
        // TODO add your handling code here:
        new MenuTajwid().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel49MouseClicked

    private void jLabel43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseClicked
        // TODO add your handling code here:
        new MenuInggris().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel43MouseClicked

    private void jLabel52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel52MouseClicked
        // TODO add your handling code here:
        new MenuKemandirian().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel52MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihMapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihMapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihMapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihMapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihMapel().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDKV;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel mNamaUstad;
    private javax.swing.JLabel txtClock;
    private javax.swing.JLabel txtStatus;
    // End of variables declaration//GEN-END:variables
}
